package com.springboot.carinsurance.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data  //Generates Getter and Setter Method for all the data members
@AllArgsConstructor  //Generates an all-args constructor
@NoArgsConstructor //Generates a no-args constructor
@Builder
@Entity  //Specifying class is an entity
@Table(name="Admin_Details")
public class Admin //Creating Admin class

{
	@Id //making id as a primary key
	@GeneratedValue(strategy=GenerationType.IDENTITY)  //making id as AutoGenerated 
	private int adminId;
	
	@NotEmpty(message = "Admin name should not be empty")   
	private String admin_name;  //Data members
	
	@NotEmpty(message = "Password should not be empty")
	private String admin_password;
	
	@Email(message= "Enter proper Email")
	private String admin_email_address;
	
	@NotNull(message="Contact no. should not be null")
	@Size(min=10, max=10)
	private String admin_contact_no;
	
	
}
