package com.springboot.carinsurance.entity;

import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data //Generates Getter and Setter Method for all the data members
@AllArgsConstructor  //Generates an all-args constructor
@NoArgsConstructor  //Generates a no-args constructor
@Entity  //Specifying class is an entity
@Table(name="Car_Details")
public class Car   //creating Car class
{
	@Id	//making id as a primary key
	@GeneratedValue(strategy=GenerationType.IDENTITY) //making id as AutoGenerated 
	private int carId;
	
	@NotBlank(message = "VIN should not be blank") 
	private String VIN;
	
	@NotEmpty(message = "car make should not be empty")   
	private String car_make;  //Data members
	
	@NotEmpty(message = "car model should not be empty")  
	private String car_model;
	
	@NotNull(message = "Date should not be null. The expected format is yyyy-MM-dd")
	private LocalDate car_manufacturing_year;
	
	@NotEmpty(message = "registration no should not be empty") 
	private String car_registration_no;
	
	@OneToOne   //creating a One-To-One relationship between a Car and Policy 
	@JoinColumn(name = "policy_id")
	private InsurancePolicy policy;

	
	
}
