package com.springboot.carinsurance.entity;



import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data //Generates Getter and Setter Method for all the data members
@AllArgsConstructor  //Generates an all-args constructor
@NoArgsConstructor  //Generates a no-args constructor
@Entity		//Specifying class is an entity
@Table(name="Claim_Details")
public class Claim 	//Creating Claim class
{
	@Id	//making id as a primary key
	@GeneratedValue(strategy=GenerationType.IDENTITY)  //making id as AutoGenerated 
	private int claimId;
	
	@NotEmpty(message = "claim no should not be empty")  
	private String claim_no;
	
	@NotNull(message="amount should not be null")
	private double claim_amount;	//Data members
	
	@NotBlank(message="status should not be blank")
	private String status;
	
	@NotNull(message = "Date should not be null. The expected format is yyyy-MM-dd")
	private LocalDate issued_date;
	
	@ManyToOne  //creating a Many-To-One relationship between a Claim and Policy 
    @JoinColumn(name = "policy_id")
    private InsurancePolicy policy;
	
}
