package com.springboot.carinsurance.entity;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data //Generates Getter and Setter Method for all the data members
@AllArgsConstructor  //Generates an all-args constructor
@NoArgsConstructor   //Generates a no-args constructor
@Entity		//Specifying class is an entity
@Table(name="InsurancePolicy_Details")
public class InsurancePolicy		//Creating InsurancePolicy class
{
	@Id	//making id as a primary key
	@GeneratedValue(strategy=GenerationType.IDENTITY)  //making id as AutoGenerated 
	private int policyId;
	
	@NotEmpty(message = "policy no should not be empty")  
	private String policy_no;
	
	@NotBlank(message = "policy type should not be blank")  
	private String policy_type;
	
	@NotNull(message="duration should not be null")
	private int duration_in_months;
	
	@NotNull(message="amount should not be null")
	private double premium_amount;
	
	@NotNull(message="amount should not be null")
	private double coverage_amount;
	
	@NotNull(message="amount should not be null")
	private double deductible_amount;
	
	@ManyToOne  //creating a Many-To-One relationship between a Policy and User 
    @JoinColumn(name = "policyholder_id")
	@JsonIgnoreProperties("insurancePolicy") 
    private User user;	

}
