package com.springboot.carinsurance.entity;


import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data //Generates Getter and Setter Method for all the data members
@AllArgsConstructor  //Generates an all-args constructor
@NoArgsConstructor  //Generates a no-args constructor
@Entity		//Specifying class is an entity
@Table(name="Payment_Details")
public class Payment		//Creating Payment class
{
	@Id	//making id as a primary key
	@GeneratedValue(strategy=GenerationType.IDENTITY)  //making id as AutoGenerated 
	private int paymentId;
	
	@NotNull(message="amount should not be null")
	private double payment_amount; 
	
	@NotNull(message = "Date should not be null. The expected format is yyyy-MM-dd")
	private LocalDate payment_date;    //data members
	
	@OneToOne  //creating a Many-To-One relationship between a Payment and Policy 
    @JoinColumn(name = "car_id")
	@JsonIgnoreProperties("payment") 
	private Car car;
}
