package com.springboot.carinsurance.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
@Data //Generates Getter and Setter Method for all the data members
@AllArgsConstructor  //Generates an all-args constructor
@NoArgsConstructor  //Generates a no-args constructor
@Entity   //Specifying class is an entity
@Table(name="Registration")
public class UserLogin 	//Creating UserLogin class
{
	@Id	//making id as a primary key
	@GeneratedValue(strategy = GenerationType.IDENTITY)  //making id as AutoGenerated 
	private int id;
	private String username;   //Data members
	private String password;
	
}
