package com.springboot.carinsurance.entity;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

 
@Data //Generates Getter and Setter Method for all the data members
@AllArgsConstructor  //Generates an all-args constructor
@NoArgsConstructor  //Generates a no-args constructor
@Entity		//Specifying class is an entity
@Table(name="User_Details")
public class User		//Creating User class
{
	@Id	//making id as a primary key
	@GeneratedValue(strategy=GenerationType.IDENTITY) //making id as AutoGenerated 
	private int userId;
	
	@NotEmpty(message = "User Name should not be empty")
	private String user_name;
	
	@NotEmpty(message = "Password should not be empty")
	private String user_password; 
	
	@NotNull(message="Contact no. should not be null")
	@Size(min=10, max=10)
	private String user_contact_no; //data members
	
	@NotBlank(message="address should not be blank")
	private String user_address;
	
}
